### ISSUE TITLE
TempoVolo

### ISSUE THREAD

**Issue by LeonardoRiselli** [LeonardoRiselli/esame_parte_I#1]
fatto prof ma non so se va bene

**Comment by FabioZTessitore** [comment]
Non va bene

**Comment by FabioZTessitore** [comment]
chi si ferma è perduto

**Comment by LeonardoRiselli** [comment]
prof ci sto pensando come far uscire le stampe d tutto

2017-03-29 18:35 GMT+02:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
in attesa

**Comment by FabioZTessitore** [comment]
ci sono addirittura errori di sintassi, il programma non gira. Prima di inviare dovresti testare

**Comment by FabioZTessitore** [comment]
nessuna novità?

**Comment by LeonardoRiselli** [comment]
non so come fare prof mi da sempre gli stessi risultati.

2017-04-23 19:29 GMT+02:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
allora?

**Comment by FabioZTessitore** [comment]
forza forza
